config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'events#index'

  resources :events do
    member do
      get :tickets
    end
  end

  resources :tickets, only: [:create, :destroy]

  resources :users, only: [:show, :update] do
    member do
      get :set_ssn
      post :save_ssn
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    can :index, Event

    if not user.new_record?
      can [:create, :destroy], Ticket, user_id: user.id
      can :manage, User, id: user.id
      can :read, Event

      if user.admin?
        can :manage, Event
        can :manage, Ticket
      end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  has_many :attendees, through: :tickets, source: :user
  has_many :tickets, dependent: :destroy

  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  validate :end_time_must_be_after_start_time

  def end_time_must_be_after_start_time
    return unless start_time and end_time
    errors.add(:end_time, "Must be after start time") if start_time > end_time
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord

  belongs_to :event
  validates :event, presence: true

  belongs_to :user
  validates :user, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  after_update :update_membership_status, if: :ssn_changed?
  before_update :reset_membership_status, if: :ssn_changed?

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :attending_events, through: :tickets, source: :event
  has_many :tickets, dependent: :destroy

  validates :ssn,
    numericality: { only_integer: true },
    allow_nil: true,
    uniqueness: true,
    length: { is: 10 }


  def attending?(event)
    attending_events.exists?(event.id)
  end

  private

  def reset_membership_status
    self.member = false
  end

  def update_membership_status
    UpdateUserMembershipJob.perform_later(User.find(self.id))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "You are not allowed to be there"
    redirect_to root_url
  end

  before_action :redirect_to_ssn_if_unset
  skip_before_action :redirect_to_ssn_if_unset, if: :devise_controller?

  def redirect_to_ssn_if_unset
    if user_signed_in? && current_user.ssn.nil?
      flash[:notice] = "We need you social security number in order to sell you tickets"
      redirect_to set_ssn_user_path(current_user)
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource

  def new
  end

  def index
  end

  def create
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def show
  end

  def tickets
  end

  private

  def event_params
    params.require(:event).permit(:title, :start_time, :end_time)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  load_and_authorize_resource

  def create
    @ticket.user = current_user
    if @ticket.save
      redirect_to @ticket.event
    else
      flash[:alert] = "Could not book ticket"
      redirect_to events_path
    end
  end

  def destroy
    redirect_to(event_path(@ticket.event)) if @ticket.destroy
  end

  private

  def ticket_params
    params.require(:ticket).permit(:event_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :redirect_to_ssn_if_unset, only: [:set_ssn, :save_ssn]
  load_and_authorize_resource

  def show
  end

  def update
    if @user.update_attributes(update_params)
      flash[:success] = "Saved new info"
      redirect_to user_path(@user)
    else
      render :show
    end
  end

  def set_ssn
  end

  def save_ssn
    if @user.update_attributes(save_ssn_params)
      flash[:success] = "Saved SSN"
      redirect_to user_path(@user)
    else
      render :set_ssn
    end
  end

  private

  def update_params
    params.require(:user).permit(:first_name, :last_name, :food_preferences)
  end

  def save_ssn_params
    params.require(:user).permit(:ssn)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_time(time)
    begin
      return time.strftime('%e %b %Y %H:%M')
    rescue
      return "Undefined"
    end
  end

  def current_user
    user = super
    user ||= User.new
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_development_helper.html.erb
<br><br>
<div class="container">
  <hr>
  <%= debug params %>
</div>

app/views/application/_flash_messages.html.erb
<% flash.each do |level, msg| %>
  <%= content_tag(:div, msg, class: "flash_#{level}") %>
<% end %>

app/views/application/_navbar.html.erb
<%= navbar static: :top do %>
  <%= navbar_header brand: 'Ticket system', brand_link: root_path %>

  <%= navbar_collapse do %>

    <%= navbar_group do %>
      <%= navbar_item 'Events', events_path %>
      <%= navbar_item 'Create event', new_event_path if can?(:create, Event)%>
    <% end %>

    <%= navbar_group align: 'right' do %>
      <%= navbar_item 'My Profile', user_path(current_user) if can?(:show, current_user) %>

      <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <%= navbar_item 'Log in', new_user_session_path %>
      <% end %>
    <% end %>

  <% end %>

<% end %>

app/views/events/_attendees_table.html.erb
<% attendees ||= @attendees %>

<table class="table table-hover">
  <tr>
    <td>First name</td>
    <td>Last name</td>
    <td>SSN</td>
    <td>Has membership</td>
    <td>Food Preferences</td>
  </tr>
  <% attendees.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.ssn %></td>
      <td class="<%= user.member ? 'success' : 'danger' %>">
        <%= user.member? ? 'Yes' : 'No' %>
      </td>
      <td><%= user.food_preferences %></td>
    </tr>
  <% end %>
</table>

app/views/events/_summary.html.erb
<% event ||= @event %>
<%= link_to event_path(event), class: "event_summary_link" do %>
  <div class="event_summary">
    <p class="title"><%= event.title %></p>
    <p class="time"><%= format_time(event.start_time) %></p>
    <p class="description">This is a placeholder for a description</p>
  </div>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>
<hr>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Start time</th>
    <th>End time</th>
  </tr>
  <% @events.each do |event| %>
    <tr>
      <td><%= link_to event.title, event_path(event) %></td>
      <td><%= format_time event.start_time %></td>
      <td><%= format_time event.end_time %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>New Event </h1>
<hr>

<%= bootstrap_form_for @event do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :start_time, { "data-provide" => "datepicker"  } %>
  <%= f.text_field :end_time, { "data-provide" => "datepicker"  } %>
  <%= f.primary %>
<% end %>

app/views/events/show.html.erb
<h1>Event</h1>
<hr>

<h3>Title</h3> <%= @event.title %>
<h3>Start Date</h3> <%= @event.start_time.strftime("%e %B") %>
<h3>End Date</h3> <%= @event.end_time.strftime("%e %B") %>
<% if can?(:create, Ticket) && !current_user.attending?(@event) %>
  <%= bootstrap_form_for Ticket.new do |f| %>
    <%= f.hidden_field :event_id, :value => @event.id %>
    <%= f.submit "Book ticket" %>
  <% end %>
<% elsif can?(:destroy, Ticket) && current_user.attending?(@event) %>
  <%= bootstrap_form_for @event.tickets.where( user_id: current_user.id).first, :method => :delete do |f| %>
    <%= f.submit "Unbook ticket" %>
  <% end %>
<% end %>

<% if can?(:manage, @event) %>
  <%= link_to "Tickets", tickets_event_path(@event), class: "btn btn-primary"%>
<% end %>

app/views/events/tickets.html.erb
<% event ||= @event %>

<%= render 'attendees_table', attendees: event.attendees %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Ticket System</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'application/navbar' %>

    <div class="container">

      <%= render 'application/flash_messages' %>

      <%= yield %>

    </div>

    <%= render 'application/development_helper' if Rails.env.development? %>

  </body>
</html>

app/views/users/_form.html.erb
<% user ||= @user %>
<%= bootstrap_form_for @user do |f| %>
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.text_field :food_preferences %>
  <%= f.text_field :ssn, disabled: true %>
  <%= f.check_box :member, disabled: true %>
  <%= f.primary "Update info" %>
<% end %>

app/views/users/set_ssn.html.erb
<h1>Set Social Security Number</h1>
<hr>

<%= bootstrap_form_for @user, url: save_ssn_user_path(@user), :method => :post do |f| %>
  <%= f.text_field :ssn, placeholder: 'YYMMDDXXX'%>
  <%= f.submit "Set SSN"%>
<% end %>

app/views/users/show.html.erb
<div class="update-info">
  <%= render 'form' %>
</div>

<h1 class="text-center">My tickets</h1>
<hr>

<% @user.attending_events.each do |event| %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= render 'events/summary', event: event %>
    </div>
  </div>
<% end %>